services:

  nginx:
    build: ./dockerfiles/nginx
    ports:
      - "8080:80"
    volumes:
      - ./dockerfiles/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/what_if
    container_name: what-if_nginx

  php:
    build: ./dockerfiles/php
    volumes:
      - .:/var/www/what_if
    container_name: what-if_php

  mysql:
    image: mysql:8.0
    container_name: what-if_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
#      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  redis:
    build: ./dockerfiles/redis
    volumes:
      - .:/var/www/what_if
    container_name: what-if_redis
    ports:
      - "6379:6379"