services:

  nginx:
    build: ./dockerfiles/nginx
    ports:
      - "8000:80"
    volumes:
      - ./dockerfiles/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dockerfiles/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/what_if
    container_name: what-if_nginx

  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    ports:
      - '${REVERB_PORT:-8080:}:8080'
    volumes:
      - .:/var/www/what_if
    container_name: what-if_php
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1G

  mysql:
    image: mysql:8.0
    container_name: what-if_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: what-if_phpmyadmin
    ports:
      - "8001:80"
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      PMA_HOST: mysql

  redis:
    build: ./dockerfiles/redis
    volumes:
      - .:/var/www/what_if
    container_name: what-if_redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
#          cpus: '2.0'
          memory: 400MB